-- insert into empleado (id, nombres, apellidos, sueldo, rol_id) values (1, 'Thom', 'Staker', 736, 2);
insert into empleado (id, nombres, apellidos, sueldo, rol_id) values (2, 'Jacquelynn', 'Hedde', 835, 3);
-- insert into empleado (id, nombres, apellidos, sueldo, rol_id) values (3, 'Bella', 'Bustard', 614, 2);
insert into empleado (id, nombres, apellidos, sueldo, rol_id) values (4, 'Lisa', 'Boig', 831, 3);
insert into empleado (id, nombres, apellidos, sueldo, rol_id) values (5, 'Colette', 'Albasini', 803, 2);
insert into empleado (id, nombres, apellidos, sueldo, rol_id) values (6, 'Callean', 'Rickarsey', 893, 2);
insert into empleado (id, nombres, apellidos, sueldo, rol_id) values (7, 'Carolina', 'Marrow', 806, 3);
insert into empleado (id, nombres, apellidos, sueldo, rol_id) values (8, 'Katuscha', 'Wiggington', 675, 3);
insert into empleado (id, nombres, apellidos, sueldo, rol_id) values (9, 'Sergeant', 'Birrane', 605, 2);
insert into empleado (id, nombres, apellidos, sueldo, rol_id) values (10, 'Ronni', 'Kamen', 794, 2);
insert into empleado (id, nombres, apellidos, sueldo, rol_id) values (11, 'Jodi', 'Olennikov', 653, 2);
insert into empleado (id, nombres, apellidos, sueldo, rol_id) values (12, 'Bessie', 'Rembrant', 739, 2);
insert into empleado (id, nombres, apellidos, sueldo, rol_id) values (13, 'Bernadina', 'Frisdick', 874, 2);
insert into empleado (id, nombres, apellidos, sueldo, rol_id) values (14, 'Franzen', 'Mulmuray', 690, 3);
insert into empleado (id, nombres, apellidos, sueldo, rol_id) values (15, 'Dulcia', 'Hagger', 877, 2);
insert into empleado (id, nombres, apellidos, sueldo, rol_id) values (16, 'Elston', 'Jepensen', 728, 3);
insert into empleado (id, nombres, apellidos, sueldo, rol_id) values (17, 'Vannie', 'Westoff', 630, 3);
insert into empleado (id, nombres, apellidos, sueldo, rol_id) values (18, 'Marcellus', 'Opfer', 713, 2);
insert into empleado (id, nombres, apellidos, sueldo, rol_id) values (19, 'Valle', 'Dovington', 895, 2);
insert into empleado (id, nombres, apellidos, sueldo, rol_id) values (20, 'Barris', 'Boxall', 783, 3);
